# Generated by Django 5.1.5 on 2025-01-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlansAndServices', '0002_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=150),
        ),
    ]
