# Generated by Django 5.1.5 on 2025-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlansAndServices', '0003_callbackrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('service_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('basic_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst', models.DecimalField(decimal_places=2, default=18.0, help_text='Enter GST percentage (adjustable by admin).', max_digits=5)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_transacted', models.BooleanField(default=False)),
            ],
        ),
    ]
