# Generated by Django 5.1.5 on 2025-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlansAndServices', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
