# Generated by Django 5.1.5 on 2025-01-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlansAndServices', '0006_promocode_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
    ]
