# Generated by Django 5.1.5 on 2025-02-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlansAndServices', '0007_remove_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
