# Generated by Django 5.1.5 on 2025-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlansAndServices', '0008_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
